language: python

before_install:
  - pip install tox
  - pip install coveralls
  - pyenv install 2.6.9
  - pyenv install 2.7
  - pyenv install 3.2
  - pyenv install 3.3.5

script:
  - tox -e py26,py27,py32,py33

after_success:
  - coveralls

