language: python
python: 2.7

env:
  - TOX_ENV=py27
  - TOX_ENV=py33
  - TOX_ENV=py34
  - TOX_ENV=py35
  - TOX_ENV=pypy
  - TOX_ENV=pypy3

before_install:
  - pip install tox
  - pip install coverage
  - pip install coveralls

script:
  - tox -e $TOX_ENV

after_success:
  - coverage combine
  - coveralls
