language: python
python: 2.7

env:
  - TOX_ENV=py26
  - TOX_ENV=py27
  - TOX_ENV=pypy
  - TOX_ENV=py32
  - TOX_ENV=py33

before_install:
  - pip install tox
  - pip install coveralls

script:
  - tox -e $TOX_ENV

after_success:
  - coveralls
